version: '3.8'

services:

  mysql:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: data_storage
    restart: always
    volumes:
      - mysql_storage:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin
    ports:
      - '8888:80'
    environment:
      PMA_HOST: mysql
      UPLOAD_LIMIT: 300M
    restart: always

volumes:
  mysql_storage:

